# ENLACES DE INICIAR SESION
POST http://127.0.0.1:5000/cus_routes1/login
Content-Type: application/json

{
    "email": "david.fernandez6@unmsm.edu.pe",
    "contrasenia": "david2024",
    "id_tipo_usuario": 3
}
##########


POST http://127.0.0.1:5000/cus_routes2/realizar_test
Content-Type: application/json

{
    "id_paciente": 1,
    "id_test": 1,
    "respuestas": "1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2"
}
##########


POST http://127.0.0.1:5000/cus_routes2/calcular_puntaje
Content-Type: application/json

{
    "id_evaluacion": 25
}