# ENLACES DE INICIAR SESION
POST http://127.0.0.1:5000/cus_routes1/login
Content-Type: application/json

{
    "email": "david.fernandez6@unmsm.edu.pe",
    "contrasenia": "david2024",
    "id_tipo_usuario": 3
}
##########


POST http://127.0.0.1:5000/cus_routes/realizar_test
Content-Type: application/json

{
    "id_estudiante": 1,
    "id_test": 1,
    "respuestas": "1, 0, 1, 2, 1, 0, 1, 0",
    "fec_realizacion": "2021-06-01"
}
##########


POST http://127.0.0.1:5000/cus_routes/calcular_puntaje
Content-Type: application/json

{
    "id_evaluacion": 14
}