# ENLACES DE ESPECIALISTA (COMPLETO)
POST http://127.0.0.1:5000/especialista_routes/create_especialista
Content-Type: application/json

{
    "id_especialidad": 1,
    "doc_identidad": "76542988",
    "nombres": "María Nicolle",
    "apellidos": "Seminario Valdivia",
    "fec_nacimiento": "2000-02-01",
    "id_genero": 2,
    "n_licencia": "123456",
    "anio_graduacion": 2018,
    "activo": true,
    "id_usuario": 9
}
#####

GET http://127.0.0.1:5000/especialista_routes/get_especialistas
#####

GET http://127.0.0.1:5000/especialista_routes/get_especialista/2
#####

PUT http://127.0.0.1:5000/especialista_routes/update_especialista/2
Content-Type: application/json

{
    "id_especialidad": 1,
    "doc_identidad": "76542988",
    "nombres": "María Luisa",
    "apellidos": "Seminario Valdivia",
    "fec_nacimiento": "2000-02-01",
    "id_genero": 2,
    "n_licencia": "123456",
    "anio_graduacion": 2018,
    "activo": true,
    "id_usuario": 9
}
#####

DELETE http://127.0.0.1:5000/especialista_routes/delete_especialista/2
#####