# ENLACES DE ESPECIALISTA
POST http://127.0.0.1:5000/especialista_routes/create_especialista
Content-Type: application/json

{
    "id_especialidad": 1,
    "doc_identidad": "76542988",
    "nombres": "María Nicolle",
    "apellidos": "Seminario Valdivia",
    "fec_nacimiento": "2000-02-01",
    "id_genero": 2,
    "email": "maria.seminario@gmail.com",
    "n_licencia": "123456",
    "anio_graduacion": 2018,
    "contrasenia": "marianicolle"
}
#####

GET http://127.0.0.1:5000/especialista_routes/get_especialistas
#####

GET http://127.0.0.1:5000/especialista_routes/get_especialista/16
#####

PUT http://127.0.0.1:5000/especialista_routes/update_especialista/17
Content-Type: application/json

{
    "id_especialidad": 2,
    "doc_identidad": "76542988",
    "nombres": "María Nicolle",
    "apellidos": "Seminario Valdivia",
    "fec_nacimiento": "2000-02-01",
    "id_genero": 2,
    "email": "maria.seminario@gmail.com",
    "n_licencia": "123456",
    "anio_graduacion": 2018,
    "contrasenia": "123456"
}
#####

DELETE http://127.0.0.1:5000/especialista_routes/delete_especialista/16
#####