# ENLACES DE LIBRETA
POST http://127.0.0.1:5000/libreta_routes/create_libreta
Content-Type: application/json

{
    "id_estudiante": 1,
    "per_academico": "2022-II",
    "nota_promedio": 15.6,
    "observaciones": "Estudiante destacado"
}
#####

GET http://127.0.0.1:5000/libreta_routes/get_libretas
#####

GET http://127.0.0.1:5000/libreta_routes/get_libreta/12
#####

PUT http://127.0.0.1:5000/libreta_routes/update_libreta/12
Content-Type: application/json

{
    "id_estudiante": 1,
    "per_academico": "2022-II",
    "nota_promedio": 15.6,
    "observaciones": "Estudiante promedio"
}
#####

DELETE http://127.0.0.1:5000/libreta_routes/delete_libreta/12
#####