# ENLACES DE USUARIO (COMPLETO)
POST http://127.0.0.1:5000/usuario_routes/create_usuario
Content-Type: application/json

{
    "email": "venom@gmail.com",
    "contrasenia": "venom2024",
    "id_tipo_usuario": 1
}
#####

GET http://127.0.0.1:5000/usuario_routes/get_usuarios
#####

GET http://127.0.0.1:5000/usuario_routes/get_usuario/1
#####

PUT http://127.0.0.1:5000/usuario_routes/update_usuario/1
Content-Type: application/json

{
    "email": "carolina.seminario@unmsm.edu.pe",
    "contrasenia": "carolina2024",
    "id_tipo_usuario": 3
}
#####

DELETE http://127.0.0.1:5000/usuario_routes/delete_usuario/6
#####